#!/bin/bash

## Get Brightness
get_blight() {
	while true; do
	value=$((255 * (brightnessctl get) / 64750))
  	echo "$value"
		sleep 15
	done
}

## Set Brightness
set_blight() {
	value=$((64750 * $1 / 255))
        brightnessctl set "$value"
}



if [[ "$1" == "--get" ]]; then
	get_blight
elif [[ "$1" == "--set" ]]; then
	set_blight "$2"
fi
