#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.background"
CFG="$HOME/.config/eww/background"

 
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	eww --config "$CFG" open background
 else
 	eww --config "$CFG" close background
 	rm "$FILE"
 fi

