########## keybinds ##########

$mainMod = ALT
$terminal = kitty
$menu = bash ~/.config/rofi/launcher.sh
$browser = firefox
$code = code

# Binds
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, M, exit, 
bind = $mainMod, F, exec, $browser
bind = $mainMod, D, exec, $menu
bind = $mainMod, backspace, killactive
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, exec, $code
bind = $mainMod, A, togglefloating
bind = $mainMod, T, exec, $terminal --class floating

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, u
bind = $mainMod, K, movefocus, d

#Mouse binds
bindm = ALT,mouse:272,movewindow



#bind=$mainMod,Return,exec,foot
#bind=$mainMod,t,exec,thunar

#bind=$mainMod,Tab,cyclenext
#bind=$mainMod,Q,killactive,

#bind=$mainMod,SPACE,exec,bash ~/.config/rofi/launcher.sh
#bind=$mainMod,p,exec,bash ~/.config/rofi/powermenu.sh
#bind=$mainMod,n,exec,bash ~/.config/wofi/network/network.sh
#bind=$mainMod,d,exec,bash ~/.config/eww/scripts/launch_dashboard
#bind=$mainMod,b,exec,swaybg -i ~/.config/hypr/background


# swap windows
bind=$mainMod,left,movewindow,l
bind=$mainMod,down,movewindow,d
bind=$mainMod,up,movewindow,u
bind=$mainMod,right,movewindow,r

# change workspace
bind=$mainMod,1,workspace,1
bind=$mainMod,2,workspace,2
bind=$mainMod,3,workspace,3
bind=$mainMod,4,workspace,4
bind=$mainMod,5,workspace,5
bind=$mainMod,6,workspace,6
bind=$mainMod,7,workspace,7
bind=$mainMod,8,workspace,8
bind=$mainMod,9,workspace,9
bind=$mainMod,0,workspace,10

# move window to given workspace
bind=SUPER,1,movetoworkspace,1
bind=SUPER,2,movetoworkspace,2
bind=SUPER,3,movetoworkspace,3
bind=SUPER,4,movetoworkspace,4
bind=SUPER,5,movetoworkspace,5
bind=SUPER,6,movetoworkspace,6
bind=SUPER,7,movetoworkspace,7
bind=SUPER,8,movetoworkspace,8
bind=SUPER,9,movetoworkspace,9
bind=SUPER,0,movetoworkspace,10

# toggle float on active window

##### screenshot #####
#bind=$mainModSHIFT,F12,exec, grim -g "$(slurp)" "$(~/Pictures/screenshots)/$(date).png"
#bind=$mainMod,F12,exec, grim "$(~/Pictures/screenshots)/$(date).png"

bind=$mainMod,F12,exec, hyprshot -m region --clipboard-only

##### toggle fullscreen #####
bind=$mainMod,f11,fullscreen,0

# volume #
bind=$mainMod,F2,exec, bash ~/.config/hypr/scripts/volume --down
bind=$mainMod,F3,exec, bash ~/.config/hypr/scripts/volume --up

# brightness #
bind=$mainMod,F5,exec, brightnessctl set 5%-
bind=$mainMod,F6,exec, brightnessctl set 5%+
